trigger:
  branches:
    include:
      - dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'
  imageName: 'devops-django'
  dockerRegistryServiceConnection: 'acr-connection-henry'  # nombre de conexión a ACR
  containerRegistry: 'devopsregistryhenry.azurecr.io'       # nombre de ACR
  tag: '$(Build.BuildId)'

stages:
  - stage: BuildAndTest
    jobs:
      - job: DjangoTests
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install flake8 coverage
            displayName: 'Instalar dependencias y herramientas de análisis'

          - script: |
              python manage.py test
            displayName: 'Ejecutar tests'

          - script: |
              flake8 . || echo "Flake8 terminó con warnings"
            displayName: 'Análisis estático con flake8 (no bloqueante)'

          - script: |
              coverage run manage.py test
              coverage report
            displayName: 'Medir cobertura de código'

  - stage: BuildAndPushImage
    dependsOn: BuildAndTest
    jobs:
      - job: DockerBuild
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: '**/Dockerfile'
              tags: |
                $(tag)
                latest

  - stage: DeployToAKS
    displayName: 'Deploy to AKS'
    dependsOn: BuildAndPushImage
    jobs:
      - job: Deploy
        displayName: 'kubectl apply'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            clean: true
          - task: Kubernetes@1
            displayName: 'Deploy manifests to AKS'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'aks-arm-connection'
              azureResourceGroup: 'devops'
              kubernetesCluster: 'aks-devops-henry'
              useClusterAdmin: true
              namespace: default
              command: apply
              useConfigurationFile: true
              configuration: >
                k8s/configmap.yaml
                k8s/deployment.yaml
                k8s/service.yaml
                k8s/ingress.yaml


